import type { Answer } from "./types";
import type { DynamicReport } from "./store";
import { QUESTIONS, applySeed } from "./mockData";

export interface ReportSection {
  title: string;
  emoji: string;
  items: { label: string; value: string; isTodo?: boolean }[];
}

interface BuildArgs {
  seed: string;
  followupAnswer: string;
  answers: Record<string, Answer>;
}

const SECTION_MAP: { title: string; emoji: string; categories: string[] }[] = [
  { title: "한 줄 요약", emoji: "💡", categories: ["value"] },
  { title: "타겟 & 핵심 문제", emoji: "🎯", categories: ["target", "problem"] },
  { title: "솔루션 & 차별점", emoji: "⚙️", categories: ["solution", "differentiator"] },
  { title: "비즈니스 모델 & 가격", emoji: "💰", categories: ["bm", "pricing"] },
  { title: "채널 & 초기 마케팅", emoji: "📣", categories: ["channel", "marketing"] },
  { title: "성장 전략 (MVP · 지표 · 마일스톤)", emoji: "🚀", categories: ["mvp", "metric", "milestone"] },
  { title: "팀 · 경쟁 환경", emoji: "👥", categories: ["team", "competitor"] },
  { title: "리스크 & 다음 액션", emoji: "⚠️", categories: ["risk", "nextAction"] },
];

export interface BuildMarkdownOpts {
  step1Only?: boolean;
  score?: number;
  /**
   * If provided, the MD body uses the LLM-synthesized report instead of
   * the raw user answers. Used by /report MD download. Ignored when
   * step1Only is true (wow-moment 1p download stays raw for immediacy).
   */
  dynamicReport?: DynamicReport | null;
}

/**
 * Renders the current plan state as a downloadable Markdown document.
 * - step1Only=true: only includes answers to Step 1 (6 questions). 1p preview snapshot.
 * - dynamicReport provided + !step1Only: render from LLM-synthesized sections.
 * - otherwise: render from raw user answers (template).
 */
export function buildMarkdown(
  args: BuildArgs,
  { step1Only = false, score, dynamicReport }: BuildMarkdownOpts = {}
): string {
  const { seed, followupAnswer, answers } = args;
  const date = new Date().toLocaleDateString("ko-KR");
  const versionLabel = step1Only
    ? "Step 1 · 미니 기획안 (1p)"
    : "Step 1+2 · 확장 기획안 (2p · 무료 마지노선)";

  const out: string[] = [];
  out.push(`# ${seed || "이 아이디어"}`);
  out.push("");
  if (followupAnswer) {
    out.push(`> 보충: ${followupAnswer}`);
    out.push("");
  }

  const meta: string[] = [`**버전:** ${versionLabel}`, `**생성일:** ${date}`];
  if (typeof score === "number") meta.push(`**실현가능성 점수:** ${score}%`);
  out.push(meta.join("  \n"));
  out.push("");
  out.push("---");
  out.push("");

  if (dynamicReport && !step1Only) {
    // ─── LLM-synthesized rendering ───
    out.push("## 💡 한 줄 요약");
    out.push("");
    out.push(dynamicReport.pitch);
    out.push("");

    for (const section of dynamicReport.sections) {
      if (section.title === "한 줄 요약") continue; // already rendered as pitch
      out.push(`## ${section.emoji} ${section.title}`);
      out.push("");
      for (const item of section.items) {
        const tag = item.isTodo ? " ⚠️ *(To-Do — 시장 검증 필요)*" : "";
        out.push(`- **${item.label}**${tag}  `);
        out.push(`  ${item.value}`);
      }
      out.push("");
    }
  } else {
    // ─── Template rendering from raw answers (used for Step 1 1p download) ───
    for (const section of SECTION_MAP) {
      const lines: string[] = [];
      for (const cat of section.categories) {
        const q = QUESTIONS.find((qq) => qq.category === cat);
        if (!q) continue;
        if (step1Only && q.step !== 1) continue;
        const a = answers[q.id];
        if (!a) continue;
        const tag = a.isTodo ? " ⚠️ *(To-Do — 시장 검증 필요)*" : "";
        lines.push(`- **${q.sectionTitle}**${tag}  `);
        lines.push(`  ${applySeed(a.text, seed)}`);
      }
      if (lines.length === 0) continue;
      out.push(`## ${section.emoji} ${section.title}`);
      out.push("");
      out.push(...lines);
      out.push("");
    }
  }

  // Aggregate To-Do summary (full report only)
  if (!step1Only) {
    const todos = Object.values(answers).filter((a) => a.isTodo);
    if (todos.length > 0) {
      out.push("---");
      out.push("");
      out.push("## ⚠️ 미결정 사항 (To-Do)");
      out.push("");
      for (const t of todos) {
        const q = QUESTIONS.find((qq) => qq.id === t.questionId);
        if (q) out.push(`- [ ] **${q.sectionTitle}** — ${q.prompt}`);
      }
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push("*Generated by ThinkPick MVP*");
  out.push("");

  return out.join("\n");
}

export function makeFilename(seed: string, step1Only: boolean): string {
  const slug =
    seed
      .trim()
      .replace(/[\\/:*?"<>|]/g, "")
      .slice(0, 30)
      .trim() || "thinkpick";
  return `${slug}-기획안-${step1Only ? "1p" : "2p"}.md`;
}
